import Document, {
  DocumentInitialProps,
  DocumentContext,
  Html,
  Main,
  NextScript,
  Head
} from 'next/document'
import React, { ReactElement } from 'react'

export default class MyDocument extends Document {
  // static async getInitialProps(ctx: DocumentContext): Promise<DocumentInitialProps> {
  // }

  render(): ReactElement {
    return (
      <Html lang='en'>
        <Head>
          <meta name='description' content='Generated by create next app' />
          <meta charSet='utf-8' />
          <meta name='theme-color' content='#000000' />
          <link rel='icon' href='/favicon.ico' />
          <link
            rel='apple-touch-icon'
            sizes='76x76'
            href='/img/brand/apple-icon.png'
          />
        </Head>
        <body className='text-slate-900 antialiased'>
          <div id='page-transition'></div>
          <Main />
          <NextScript />
        </body>
      </Html>
    )
  }
}
